version: '3.8'

services:
  # [Gateway] Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend-core/media:/app/media
    depends_on:
      - backend-core
      - backend-chat

  # [Main Server] Django
  backend-core:
    build: ./backend-core
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend-core:/app
      - ./backend-core/media:/app/media
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  # [Chat Server] FastAPI
  backend-chat:
    build: ./backend-chat
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./backend-chat:/app
    ports:
      - "8001:8001"
    environment:
      - TZ=Asia/Seoul
      - REDIS_HOST=redis
    depends_on:
      - redis

  # [DB] PostgreSQL
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # [Message Broker] Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: