import random as rd
import smtplib
from email.message import EmailMessage
from django.core.cache import cache
from django.conf import settings # settings.py의 설정을 가져옵니다.
from dotenv import load_dotenv
import os

load_dotenv()

def extract_univ(raw_email):
    if '@' not in raw_email:
        return None
    
    domain = raw_email.split('@')[-1].strip().lower()
    email_dic = {
        "ajou.ac.kr" : "Ajou University",
        "andong.ac.kr" : "Andong National University",
        "acts.ac.kr" : "Asian United Theological University",
        "bu.ac.kr" : "Baekseok University",
        "bnue.ac.kr" : "Busan National University of Education",
        "bpu.ac.kr" : "Busan Presbyterian University",
        "bufs.ac.kr" : "Busan University of Foreign Studies",
        "cataegu.ac.kr" : "Catholic University of Taegu-Hyosung",
        "cau.ac.kr" : "Chung-Ang University",
        "changwon.ac.kr" : "Changwon National University",
        "charusat.ac.in" : "Charotar University of Science and Technology",
        "cheju.ac.kr" : "Cheju National University",
        "cheju-e.ac.kr" : "Cheju National University of Education",
        "chinju.ac.kr" : "Chinju National University",
        "chinju-e.ac.kr" : "Chinju National University of Education",
        "chodang.ac.kr" : "Chodang University",
        "chonbuk.ac.kr" : "Chonbuk National University",
        "chongju.ac.kr" : "Chongju University",
        "chongju-e.ac.kr" : "Chongju National University of Education",
        "chonju-e.ac.kr" : "Chonju National University of Education",
        "chonnam.ac.kr" : "Chonnam National University",
        "chosun.ac.kr" : "Chosun University",
        "chungbuk.ac.kr" : "Chungbuk National University",
        "chungju.ac.kr" : "Chung-Ju National University",
        "chungnam.ac.kr" : "Chungnam National University",
        "cnue-e.ac.kr" : "Chunchon National University of Education",
        "cuk.ac.kr" : "Catholic University of Korea",
        "cup.ac.kr" : "Catholic University of Pusan",
        "cha.ac.kr" : "CHA University",
        "cju.ac.kr" : "CHEONGJU UNIVERSITY",
        "cku.ac.kr" : "Catholic Kwandong University",
        "cs.ac.kr" : "Changshin University",
        "cje.ac.kr" : "Cheongju National University of Education",
        "chongshin.ac.kr" : "Chongshin University",
        "chugye.ac.kr" : "Chugye University for the Arts",
        "cnue.ac.kr" : "Chuncheon National University of Education",
        "chungwoon.ac.kr" : "Chungwoon University",
        "daebul.ac.kr" : "Daebul University",
        "dankook.ac.kr" : "Dankook University",
        "donga.ac.kr" : "Dong-A University",
        "dongduk.ac.kr" : "Dongduk Women's University",
        "dongeui.ac.kr" : "Dong Eui University",
        "dongguk.ac.kr" : "Dongguk University",
        "dongseo.ac.kr" : "Dongseo University",
        "dongshinu.ac.kr" : "Dongshin University",
        "duksung.ac.kr" : "Duksung Women's University",
        "dytc.ac.kr" : "Dong Yang University of Technology",
        "tau.ac.kr" : "Daegu Arts University",
        "dgist.ac.kr" : "Daegu Gyeongbuk Institute of Science and Technology",
        "dhu.ac.kr" : "Daegu Haany University",
        "dnue.ac.kr" : "Daegu National University of Education",
        "daegu.ac.kr" : "Daegu University",
        "dufs.ac.kr" : "Daegu University of Foreign Studies",
        "dcatholic.ac.kr" : "Daejeon Catholic University",
        "daejeon.ac.kr" : "Daejeon Theological University",
        "dju.ac.kr" : "Daejeon University",
        "daejin.ac.kr" : "Daejin University",
        "daeshin.ac.kr" : "Daeshin University",
        "deu.ac.kr" : "Dong-Eui University",
        "dyu.ac.kr" : "Dongyang University",
        "ewha.ac.kr" : "Ewha Womans University",
        "eulji.ac.kr" : "Eulji University",
        "kdu.ac.kr" : "Far East University",
        "gachon.ac.kr" : "Gachon University",
        "gwnu.ac.kr" : "Gangneung-Wonju National University",
        "ggu.ac.kr" : "Geumgang University",
        "gimcheon.ac.kr" : "Gimcheon University",
        "gjue.ac.kr" : "Gongju National University of Education",
        "gjcatholic.ac.kr" : "Gwangju Catholic University",
        "gist.ac.kr" : "Gwangju Institute of Science and Technology",
        "gnue.ac.kr" : "Gwangju National University of Education",
        "ginue.ac.kr" : "Gyeongin National University of Education",
        "gntech.ac.kr" : "Gyeongnam National University of Science and Technology",
        "gsnu.ac.kr" : "Gyeongsang National University",
        "hallym.ac.kr" : "Hallym University",
        "hangkong.ac.kr" : "Hankuk Aviation University",
        "hannam.ac.kr" : "Hannam University",
        "hansei.ac.kr" : "Hansei University",
        "hanseo.ac.kr" : "Hanseo University",
        "hanshin.ac.kr" : "Hanshin University",
        "hansung.ac.kr" : "Hansung University Seoul",
        "hanyang.ac.kr" : "Hanyang University",
        "hknu.ac.kr" : "Hankyong National University",
        "honam.ac.kr" : "Honam University",
        "hongik.ac.kr" : "Hongik University",
        "hoseo.ac.kr" : "Hoseo University",
        "howon.ac.kr" : "Chonbuk Sanup University of Technology (Howon University)",
        "hufs.ac.kr" : "Hankuk University of Foreign Studies",
        "hyupsung.ac.kr" : "Hyupsung University",
        "halla.ac.kr" : "Halla University",
        "hanbat.ac.kr" : "Hanbat National University",
        "handong.edu" : "Handong Global University",
        "hanil.ac.kr" : "Hanil University and Presbyterian Theological Seminary",
        "hanlyo.ac.kr" : "Hanlyo University",
        "hanzhong.ac.kr" : "Hanzhong University",
        "htus.ac.kr" : "Honam Theological University and Seminary",
        "iccu.ac.kr" : "Incheon Catholic University",
        "inu.ac.kr" : "Incheon National University",
        "iuk.ac.kr" : "International University of Korea",
        "icu.ac.kr" : "Information and Communications University",
        "inchon.ac.kr" : "Inchon University",
        "inchon-e.ac.kr" : "Inchon National University of Education",
        "inha.ac.kr" : "Inha University",
        "inje.ac.kr" : "Inje University",
        "jeonju.ac.kr" : "Jeonju University",
        "jeju.ac.kr" : "Jeju International University",
        "jejunu.ac.kr" : "Jeju National University",
        "jnue.ac.kr" : "Jeonju National University of Education",
        "jesus.ac.kr" : "Jesus University",
        "sangha.ac.kr" : "Joong-Ang Sangha University",
        "joongbu.ac.kr" : "Joongbu University",
        "jwu.ac.kr" : "Jungwon University",
        "kaist.ac.kr" : "Korea Advanced Institute of Science & Technology",
        "kangnam.ac.kr" : "Kangnam University",
        "kangnung.ac.kr" : "Kangnung National University",
        "kangwon.ac.kr" : "Kangwon National University",
        "kaya.ac.kr" : "Kaya University",
        "kdischool.ac.kr" : "KDI School of Public Policy and Management",
        "keimyung.ac.kr" : "Keimyung University",
        "kmaritime.ac.kr" : "Korea Maritime University",
        "knou.ac.kr" : "Korea National Open University",
        "knua.ac.kr" : "Korea National University of Arts",
        "knue.ac.kr" : "Korea National University of Education",
        "knupe.ac.kr" : "Korea National University of Physical Education",
        "kongju-e.ac.kr" : "Kongju National University of Education",
        "konkuk.ac.kr" : "Konkuk University",
        "konyang.ac.kr" : "Konyang University",
        "kookmin.ac.kr" : "Kookmin University",
        "korea.ac.kr" : "Korea University",
        "kosin.ac.kr" : "Kosin University",
        "kumoh.ac.kr" : "Kumoh National University of Technology",
        "kunsan.ac.kr" : "Kunsan National University",
        "kwandong.ac.kr" : "Kwan Dong University",
        "kwangju.ac.kr" : "Kwangju University",
        "kwangju-e.ac.kr" : "Kwangju National University of Education",
        "kwangwoon.ac.kr" : "Kwangwoon University",
        "kyonggi.ac.kr" : "Kyonggi University",
        "kyongju.ac.kr" : "Kongju National University",
        "kyunghee.ac.kr" : "Kyunghee University",
        "kyungil.ac.kr" : "Kyungil University",
        "kyungnam.ac.kr" : "Kyungnam University",
        "kyungpook.ac.kr" : "Kyungpook National University",
        "kyungsung.ac.kr" : "Kyungsung University",
        "kyungwon.ac.kr" : "Kyungwon University",
        "kcu.ac.kr" : "KC University",
        "kkot.ac.kr" : "Kkottongnae University",
        "kau.ac.kr" : "Korea Aerospace University",
        "kafna.ac.kr" : "Korea Armed Forces Nursing Academy",
        "kbtus.ac.kr" : "Korea Baptist Theological University and Seminary",
        "kmou.ac.kr" : "Korea Maritime and Ocean University",
        "kma.ac.kr" : "Korea Military Academy",
        "knsu.ac.kr" : "Korea National Sport University",
        "nuch.ac.kr" : "Korea National University of Cultural Heritage",
        "kornu.ac.kr" : "Korea Nazarene University",
        "kpu.ac.kr" : "Korea Polytechnic University",
        "koreatech.ac.kr" : "Korea University of Technology and Education",
        "bible.ac.kr" : "Korean Bible University",
        "police.ac.kr" : "Korean National Police University",
        "kwu.ac.kr" : "Kwangju Women's University",
        "kwangshin.ac.kr" : "Kwangshin University",
        "khu.ac.kr" : "Kyung Hee University",
        "kduniv.ac.kr" : "Kyungdong University",
        "ikw.ac.kr" : "Kyungwoon University",
        "miryang.ac.kr" : "Miryang National University",
        "mmu.ac.kr" : "Mokpo National Maritime University",
        "mokpo.ac.kr" : "Mokpo National University",
        "mokwon.ac.kr" : "Mokwon University Taejon",
        "myongji.ac.kr" : "Myongji University",
        "mtu.ac.kr" : "Methodist Theological University",
        "mcu.ac.kr" : "Mokpo Catholic University",
        "nambu.ac.kr" : "Nambu University",
        "nsu.ac.kr" : "Namseoul University",
        "pcu.ac.kr" : "Pai Chai University",
        "puts.ac.kr" : "Presbyterian University and Theological Seminary",
        "ptu.ac.kr" : "Pyeongtaek University",
        "paichai.ac.kr" : "Paichai University",
        "pknu.ac.kr" : "Pukyong National University",
        "postech.ac.kr" : "Pohang University of Science and Technology",
        "ptuniv.ac.kr" : "Pyongtaek University",
        "pufs.ac.kr" : "Pusan University of Foreign Studies",
        "pusan.ac.kr" : "Pusan National University",
        "pusan-e.ac.kr" : "Pusan National University of Education",
        "pwc.ac.kr" : "Pusan Women's University",
        "afa.ac.kr" : "Republic of Korea Air Force Academy",
        "navy.ac.kr" : "Republic of Korea Naval Academy",
        "samchok.ac.kr" : "Samchok National University",
        "sangji.ac.kr" : "Sang Ji University",
        "sangmyung.ac.kr" : "Sang Myung University",
        "sch.ac.kr" : "Soonchunhyang University",
        "sejong.ac.kr" : "Sejong University",
        "semyung.ac.kr" : "Semyung University",
        "seonam.ac.kr" : "Seonam University",
        "seoul-e.ac.kr" : "Seoul National University of Education",
        "seowon.ac.kr" : "Seowon University",
        "silla.ac.kr" : "Silla University",
        "skku.ac.kr" : "Sung Kyun Kwan University",
        "skuniv.ac.kr" : "Seokyeong University",
        "snu.ac.kr" : "Seoul National University",
        "snut.ac.kr" : "Seoul National University of Technology",
        "sogang.ac.kr" : "Sogang University",
        "sookmyung.ac.kr" : "Sookmyung Women's University",
        "soongsil.ac.kr" : "Soongsil University",
        "stu.ac.kr" : "Seoul Teological University",
        "sunchon.ac.kr" : "Sunchon National University",
        "sungkyul.ac.kr" : "Sungkyul University",
        "sungshin.ac.kr" : "Sungshin Women's University",
        "sunmoon.ac.kr" : "Sunmoon University",
        "suwon.ac.kr" : "Suwon University",
        "suwoncatholic.ac.kr" : "Suwon Catholic University",
        "swu.ac.kr" : "Seoul Women's University",
        "syu.ac.kr" : "Sahmyook University",
        "smu.ac.kr" : "Sangmyung University",
        "sehan.ac.kr" : "Sehan University",
        "scu.ac.kr" : "Seoul Christian University",
        "hytu.ac.kr" : "Seoul Hanyoung University",
        "sjs.ac.kr" : "Seoul Jangsin University",
        "seoultech.ac.kr" : "Seoul National University of Science and Technology",
        "sgu.ac.kr" : "Shingyeong University",
        "shinhan.ac.kr" : "Shinhan University",
        "songwon.ac.kr" : "Songwon University",
        "skhu.ac.kr" : "Sungkonghoe University",
        "skku.edu" : "Sungkyunkwan University",
        "taegu.ac.kr" : "Taegu University",
        "taegu-e.ac.kr" : "Taegu National University of Education",
        "taejon.ac.kr" : "Taejon University",
        "taeshin.ac.kr" : "Taeshin Christian University",
        "tit.ac.kr" : "Tongmyung University of Information Technology",
        "tnut.ac.kr" : "Taejon National University of Technology",
        "ulsan.ac.kr" : "University of Ulsan",
        "uos.ac.kr" : "Seoul City University",
        "ust.ac.kr" : "University of Science and Technology",
        "u1.ac.kr" : "U1 University",
        "uu.ac.kr" : "Uiduk University",
        "unist.ac.kr" : "Ulsan National Institute of Science and Technology",
        "wsu.ac.kr" : "Woosong University",
        "wonkwang.ac.kr" : "Wonkwang University",
        "woosuk.ac.kr" : "Woosuk University",
        "yeungnam.ac.kr" : "Yeungnam University",
        "yonsei.ac.kr" : "Yonsei University",
        "yosu.ac.kr" : "Yosu National University",
        "www.yewon.ac.kr" : "Yewon Arts University",
        "www.yongin.ac.kr" : "Yong In University",
        "www.ysu.ac.kr" : "Youngsan University",
        "www.youngsan.ac.kr" : "Youngsan University of Son Studies",
        }

    return email_dic.get(domain)

def send_verification_email(raw_email):
    auth_code = rd.randint(100000, 999999)

    cache.set(f"auth_{raw_email}", str(auth_code), timeout=300)

    msg = EmailMessage()
    msg.set_content(f"안녕하세요! Uniquest 인증번호는 [{auth_code}] 입니다.")
    msg['Subject'] = "[Uniquest] 대학생 소속 인증 번호"
    msg['From'] = settings.EMAIL_HOST_USER
    msg['To'] = raw_email

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)
        smtp.send_message(msg)

# def send_verification_email(raw_email):
#     auth_code = rd.randint(100000, 999999)
#     cache.set(f"auth_{raw_email}", str(auth_code), timeout=300)
#     print(cache.get(f"auth_{raw_email}"))

    
def verify_code(raw_email, user_input):
    saved_code = cache.get(f"auth_{raw_email}")
    return saved_code == str(user_input)


