# Generated by Django 4.2.28 on 2026-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manner_score',
            field=models.FloatField(default=80, verbose_name='매너 온도'),
        ),
    ]
