# Generated by Django 4.2.27 on 2026-01-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='대학명')),
                ('domain', models.CharField(max_length=50, verbose_name='인증 메일 도메인 (예: yonsei.ac.kr)')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='manner_score',
        ),
        migrations.AddField(
            model_name='user',
            name='reliability_score',
            field=models.FloatField(default=36.5, verbose_name='신뢰도 점수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.university', verbose_name='소속 대학'),
        ),
    ]
