# Generated by Django 4.2.27 on 2026-01-30 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_blocked_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_people',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_people',
            field=models.ManyToManyField(blank=True, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
