# Generated by Django 4.2.28 on 2026-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
