# Generated by Django 4.2.27 on 2026-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_blocked_people_user_blocked_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reliability_score',
        ),
        migrations.AlterField(
            model_name='user',
            name='manner_score',
            field=models.FloatField(default=36.5, verbose_name='매너 온도'),
        ),
    ]
