# Generated by Django 4.2.27 on 2026-02-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_blocked_people_user_blocked_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='대학명')),
                ('domain', models.CharField(max_length=50, verbose_name='인증 메일 도메인 (예: yonsei.ac.kr)')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.university', verbose_name='소속 대학'),
        ),
    ]
