# Generated by Django 4.2.28 on 2026-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review_datas',
            field=models.JSONField(default=dict),
        ),
    ]
