# Generated by Django 4.2.28 on 2026-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_review_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='review_datas',
            field=models.JSONField(default=list),
        ),
    ]
