# Generated by Django 4.2.28 on 2026-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_review_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d/'),
        ),
    ]
