# Generated by Django 4.2.28 on 2026-02-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='univ_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='학교 이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
