# Generated by Django 4.2.28 on 2026-02-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_univ_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manner_score',
            field=models.FloatField(default=3, verbose_name='매너 온도'),
        ),
    ]
