# Generated by Django 4.2.27 on 2026-02-01 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField(blank=True)),
                ('reward', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('ERRAND', '심부름'), ('STUDY', '학업'), ('RENTAL', '대여'), ('RECRUIT', '구인'), ('LIFE', '생활'), ('OTHER', '기타')], max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'waiting'), ('MATCHED', 'matched'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='WAITING', max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=80)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('location_address', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='missions/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=40)),
                ('category', models.CharField(blank=True, choices=[('ERRAND', '심부름'), ('STUDY', '학업'), ('RENTAL', '대여'), ('RECRUIT', '구인'), ('LIFE', '생활'), ('OTHER', '기타')], max_length=20, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'is_default', 'is_active', 'order'], name='missions_ta_categor_9a22a5_idx'), models.Index(fields=['slug'], name='missions_ta_slug_1fca31_idx'), models.Index(fields=['name'], name='missions_ta_name_90ea7e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_tag_per_category_slug'),
        ),
        migrations.AddField(
            model_name='missiontag',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.tag'),
        ),
        migrations.AddField(
            model_name='missionimage',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='missions', through='missions.MissionTag', to='missions.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='missiontag',
            unique_together={('mission', 'tag')},
        ),
    ]
