# Generated by Django 4.2.27 on 2026-01-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
