# Generated by Django 4.2.28 on 2026-02-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_add_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('WAITING', 'waiting'), ('PENDING_APPROVAL', '수락 대기'), ('MATCHED', 'matched'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='WAITING', max_length=20),
        ),
    ]
