# Generated by Django 4.2.28 on 2026-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('WAITING', '대기중'), ('PENDING_APPROVAL', '수락 대기'), ('MATCHED', '진행중'), ('COMPLETED', '완료'), ('CANCELLED', '취소됨')], default='WAITING', max_length=20),
        ),
    ]
